browser=chrome
mode=headless   # headed / headless
env=prod       # stage / prod

environment.stage=https://csagscorp.wpengine.com/store/
environment.prod=https://www.csagroup.org/store/

stageUrl=https://csagscorp.wpengine.com/store/
prodUrl=https://www.csagroup.org/store/

securitycode = 78$%ghfg9)gh

#Login Credentials
username=csaqatest+feb5pr@gmail.com
password=testing11
prodUser=Testfeb5p

#Search Product Details
SearchProduct=C22.1
ProductName = CSA C22.1:24
ProductPaper = 2022461

#Create Account Details
LastName = QA
Country = Canada
State = Ontario
Industry = Educational services
NewPassword = testing11
ConfirmPassword = testing11


#stage environment credentials
stageUsername = csaqatest+04020958@gmail.com
stagePassword = testing11
stageUser = test04020958