name: CSA Env-Based Test Execution

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        default: stage
        options: [stage, prod]
      browser:
        type: choice
        default: chrome-headless
        options: [chrome-headless, chrome, edge, firefox]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     # Java SetUp
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run Regression Suite
        run: |
          mvn clean test \
          -Denv=${{ github.event.inputs.env || 'stage' }} \
          -Dbrowser=${{ github.event.inputs.browser || 'chrome' }}

